### ISSUE TITLE
Support TransactionAttribute

### ISSUE THREAD

**Issue by swr1bm86** [CityOfZion/neo-go-sdk#22]

**Comment by revett** [comment]
@zjhmale Thanks for raising an issue!

Can you please expand on the feature?

**Comment by swr1bm86** [comment]
Hi @revett, I noticed this because I'm currently developing a C++ SDK. When I walked through the Go and swift one, I found out there is no corresponding implementation in Go and the transaction attribute is commented in Swift SDK.

**Comment by swr1bm86** [comment]
I checked with @saltyskip on Slack, maybe he can expand this future here?

**Comment by revett** [comment]
@zjhmale Thanks for the reply.

Do you have any documentation about the feature, or a code example from a different SDK?

**Comment by saltyskip** [comment]
He's referring to the attributes that can be seen [here](https://github.com/CityOfZion/neo-swift/blob/master/NeoSwift/Models/TransactionAttritbute.swift)

You can pack the attribute data before the main transaction payload data as seen [here](https://github.com/CityOfZion/neo-swift/blob/master/NeoSwift/Account.swift#L170)

There are many usage types, but we just support the description attribute which will allow you to pass a short message along with the transaction

**Comment by revett** [comment]
@saltyskip Thanks!

@zjhmale Could you describe in what context you'd like to use an attribute?

**Comment by swr1bm86** [comment]
@saltyskip Thanks!

@revett I can't imagine a concrete scenario right now, I'm still quite new to the NEO ecosystem 😅  Currently, I just want to port a workable SDK in another language :)
